=== usgin/ada-metadata/schemaTests/generated-schemaOrg.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "type": "object",
    "properties": {
        "@context": {"$ref": "#/$defs/@context_type"},
        "id": {"type": "string"},
        "type": {"$ref": "#/$defs/type_type"},
        "name": {"type": "string"},
        "description": {"type": "string"},
        "additionalType": {"$ref": "#/$defs/type_type"},
        "identifier": {"type": "string"},
        "url": {"type": "string"},
        "creator": {"$ref": "#/$defs/creator_type"},
        "contributor": {"$ref": "#/$defs/contributor2_type"},
        "funding": {"$ref": "#/$defs/funding_type"},
        "license": {"$ref": "#/$defs/type_type"},
        "dateCreated": {"type": "string"},
        "dateModified": {"type": "string"},
        "datePublished": {"type": "string"},
        "creativeWorkStatus": {"type": "string"},
        "additionalProperty": {"$ref": "#/$defs/additionalProperty_type"},
        "subjectOf": {"$ref": "#/$defs/subjectOf_type"}
    },
    "$defs": {
        "@context_type": {
            "type": "array",
            "minItems": 0,
            "prefixItems": [
                {"type": "string"},
                {
                    "type": "object",
                    "properties": {
                        "dcterms": {"type": "string"},
                        "geosparql": {"type": "string"},
                        "spdx": {"type": "string"},
                        "ada": {"type": "string"},
                        "id": {"type": "string"},
                        "type": {"type": "string"}
                    }
                }
            ]
        },
        "type_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        },
        "creator_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "type": {"type": "string"},
                    "name": {"type": "string"},
                    "identifier": {"type": "string"},
                    "email": {"type": "string"}
                },
                "required": [
                    "identifier",
                    "name",
                    "id",
                    "type",
                    "email"
                ]
            }
        },
        "contributor_type": {
            "type": "object",
            "properties": {
                "@type": {"type": "string"},
                "id": {"type": "string"},
                "name": {"type": "string"},
                "identifier": {"type": "string"},
                "email": {"type": "string"}
            }
        },
        "contributor2_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "roleName": {"type": "string"},
                    "contributor": {"$ref": "#/$defs/contributor_type"}
                },
                "required": [
                    "contributor",
                    "@type",
                    "roleName"
                ]
            }
        },
        "funder_type": {
            "type": "object",
            "properties": {
                "@type": {"type": "string"},
                "name": {"type": "string"},
                "identifier": {"type": "string"}
            }
        },
        "funding_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "identifier": {"type": "string"},
                    "name": {"type": "string"},
                    "funder": {"$ref": "#/$defs/funder_type"}
                },
                "required": [
                    "funder",
                    "identifier",
                    "@type",
                    "name"
                ]
            }
        },
        "mainEntity_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "additionalType": {"type": "string"},
                    "identifier": {"type": "string"}
                },
                "required": [
                    "identifier",
                    "additionalType",
                    "@type"
                ]
            }
        },
        "measurementTechnique_type": {
            "type": "object",
            "properties": {
                "@type": {"type": "string"},
                "name": {"type": "string"},
                "termCode": {"type": "string"}
            }
        },
        "location_type": {
            "type": "object",
            "properties": {
                "identifier": {"type": "string"},
                "name": {"type": "string"},
                "alternateName": {"type": "string"}
            }
        },
        "ada:AnalysisEvent_type": {
            "type": "object",
            "properties": {
                "@type": {"type": "string"},
                "identifier": {"type": "string"},
                "endDate": {"type": "string"},
                "ada:analysis.instrument": {"$ref": "#/$defs/funder_type"},
                "location": {"$ref": "#/$defs/location_type"}
            }
        },
        "variableMeasured_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "name": {"type": "string"},
                    "ada:fieldType": {"type": "string"},
                    "description": {"type": "string"},
                    "unitText": {"type": "string"},
                    "maxValue": {"type": "number"},
                    "minValue": {"type": "number"}
                },
                "required": [
                    "@type",
                    "ada:fieldType",
                    "name",
                    "description"
                ]
            }
        },
        "size_type": {
            "type": "object",
            "properties": {
                "@type": {"type": "string"},
                "value": {"type": "integer"},
                "unitText": {"type": "string"}
            }
        },
        "relatedLink_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "linkrelationship": {"type": "string"},
                    "name": {"type": "string"}
                },
                "required": [
                    "@type",
                    "name",
                    "linkrelationship"
                ]
            }
        },
        "hasPart_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "additionalType": {"type": "string"},
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "about": {"$ref": "#/$defs/type_type"},
                    "spdx:checksum": {"type": "string"},
                    "variableMeasured": {"$ref": "#/$defs/variableMeasured_type"},
                    "ada:countRows": {"type": "integer"},
                    "ada:countColumns": {"type": "integer"},
                    "ada:headerRowCount": {"type": "integer"},
                    "size": {"$ref": "#/$defs/size_type"},
                    "encodingFormat": {"type": "string"},
                    "relatedLink": {"$ref": "#/$defs/relatedLink_type"},
                    "ada:numPixelsX": {"type": "integer"},
                    "ada:numPixelsY": {"type": "integer"}
                },
                "required": [
                    "additionalType",
                    "size",
                    "@type",
                    "name",
                    "about",
                    "encodingFormat",
                    "spdx:checksum"
                ]
            }
        },
        "value_type": {
            "type": "object",
            "properties": {
                "mainEntity": {"$ref": "#/$defs/mainEntity_type"},
                "measurementTechnique": {"$ref": "#/$defs/measurementTechnique_type"},
                "ada:AnalysisEvent": {"$ref": "#/$defs/ada:AnalysisEvent_type"},
                "hasPart": {"$ref": "#/$defs/hasPart_type"}
            }
        },
        "additionalProperty_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@type": {"type": "string"},
                    "propertyID": {"type": "string"},
                    "description": {"type": "string"},
                    "value": {"$ref": "#/$defs/value_type"}
                },
                "required": [
                    "@type",
                    "description",
                    "propertyID",
                    "value"
                ]
            }
        },
        "dcterms:conformsTo_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@id": {"type": "string"}
                },
                "required": ["@id"]
            }
        },
        "subjectOf_type": {
            "type": "object",
            "properties": {
                "@id": {"type": "string"},
                "@type": {"type": "string"},
                "dateModified": {"type": "string"},
                "creator": {"$ref": "#/$defs/creator_type"},
                "about": {"type": "string"},
                "description": {"type": "string"},
                "dcterms:conformsTo": {"$ref": "#/$defs/dcterms:conformsTo_type"}
            }
        }
    }
}

=== usgin/ada-metadata/schemaTests/EMPA_j16b-6288-schemaOrg.json
{
    "@context": [
        "https://schema.org/",
        {
            "dcterms": "http://purl.org/dc/terms/",
            "geosparql": "http://www.opengis.net/ont/geosparql#",
            "spdx": "http://spdx.org/rdf/terms#",
            "ada": "https://ada.astromat.org/metadata/",
            "id": "@id",
            "type": "@type"
        }
    ],
    "id": "ada:668076",
    "type": [
        "Dataset",
        "Product"
    ],
    "name": "Major element composition of olivine and carbonates measured for oxygen isotopic compositions by SIMS in OREX-800045-103",
    "description": "Here we report the major element composition of olivine and carbonate grains that have been measured at CRPG for their oxygen isotopic composition in the fine-grained material of three particles of OREX-800045-103.",
    "additionalType": ["Electron microprobe analysis"],
    "identifier": "https://doi.org/10.60707/j16b-6288",
    "url": "https://ada.astromat.org/doi/10.60707/j16b-6288",
    "creator": [
        {
            "id": "https://ada.org/person/1234",
            "type": "Person",
            "name": "Piani, Laurette",
            "identifier": "https://orcid.org/0000-0003-0854-7468",
            "email": "laurette.piani@univ-lorraine.fr"
        }
    ],
    "contributor": [
        {
            "@type": "Role",
            "roleName": "Researcher",
            "contributor": {
                "@type": "Person",
                "id": "https://ada.org/person/437",
                "name": "Marrocchi, Yves",
                "identifier": "https://orcid.org/0000-0001-7075-3698",
                "email": "yvesm@crpg.cnrs-nancy.fr"
            }
        },
        {
            "@type": "Role",
            "roleName": "Researcher",
            "contributor": {
                "@type": "Person",
                "id": "https://ada.org/person/6968",
                "name": "Villeneuve, Johan",
                "identifier": "https://orcid.org/0000-0002-9892-8530",
                "email": "johan.villeneuve@univ-lorraine.fr"
            }
        }
    ],
    "funding": [
        {
            "@type": "MonetaryGrant",
            "identifier": "NNM10AA11C",
            "name": "New Frontiers program",
            "funder": {
                "@type": "Organization",
                "name": "National Aeronautics and Space Administration",
                "identifier": "https://ror.org/027ka1x80"
            }
        }
    ],
    "license": ["URI for license"],
    "dateCreated": "2024-07-10T14:15:05",
    "dateModified": "2025-01-27T23:18:47",
    "datePublished": "2025-12-31T00:00:00",
    "creativeWorkStatus": "Calibration and Validation",
    "additionalProperty": [
        {
            "@type": "PropertyValue",
            "propertyID": "ada:productDetail",
            "description": "these are ADA specific properties, extending the base CDIF discovery profile",
            "value": {
                "mainEntity": [
                    {
                        "@type": "Thing",
                        "additionalType": "MaterialSample",
                        "identifier": "OREX-800045-103"
                    }
                ],
                "measurementTechnique": {
                    "@type": "DefinedTerm",
                    "name": "Electron microprobe analysis",
                    "termCode": "EMPA"
                },
                "ada:AnalysisEvent": {
                    "@type": "Event",
                    "identifier": "20240603_EMPA_CNRS-CRPG_OREX-800045-103_1",
                    "endDate": "2024-06-03T08:33:44+00:00",
                    "ada:analysis.instrument": {
                        "@type": "Thing",
                        "name": "JEOL JXA-8230",
                        "identifier": "JXA-8230"
                    },
                    "location": {
                        "identifier": "https://ror.org/011nqat45",
                        "name": "Centre de Recherches Petrographiques et Geochimiques (Nancy, France)",
                        "alternateName": "CNRS-CRPG"
                    }
                },
                "hasPart": [
                    {
                        "@type": "Dataset",
                        "additionalType": "ada:EMPAQEATabular",
                        "name": "20240603_EMPA_CNRS-CRPG_OREX-800045-103_1_EMPAQEATabular_1.csv",
                        "description": "EMPA analyses of the olivine and carbonate grains of OREX-800045-103 (raw data)",
                        "about": ["major elements"],
                        "spdx:checksum": "5cf92da129c777b03eefad6b3648042be61a45b6c6eca900c757f2996450b65c",
                        "variableMeasured": [
                            {
                                "@type": "PropertyValue",
                                "name": "Analysis",
                                "ada:fieldType": "string",
                                "description": "Name of the analysis"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "SiO2",
                                "unitText": "Mass%",
                                "maxValue": 55.34,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of SiO2 in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "Al2O3",
                                "unitText": "Mass%",
                                "maxValue": 54.6,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of Al2O3 in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "CaO",
                                "unitText": "Mass%",
                                "maxValue": 57.56,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of CaO in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "Cr2O3",
                                "unitText": "Mass%",
                                "maxValue": 61.12,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of Cr2O3 in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "MgO",
                                "unitText": "Mass%",
                                "maxValue": 58.48,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of MgO in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "FeO",
                                "unitText": "Mass%",
                                "maxValue": 68.51,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of FeO in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "MnO",
                                "unitText": "Mass%",
                                "maxValue": 4.59,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of MnO in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "TiO2",
                                "unitText": "Mass%",
                                "maxValue": 0.18,
                                "minValue": 0,
                                "ada:fieldType": "decimal",
                                "description": "Abundance of TiO2 in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "Total",
                                "unitText": "Mass%",
                                "maxValue": 103.53,
                                "minValue": 26.8,
                                "ada:fieldType": "decimal",
                                "description": "Total in wt%"
                            },
                            {
                                "@type": "PropertyValue",
                                "name": "Comments",
                                "ada:fieldType": "string",
                                "description": "comments on the analysis location"
                            }
                        ],
                        "ada:countRows": 108,
                        "ada:countColumns": 13,
                        "ada:headerRowCount": 11,
                        "size": {
                            "@type": "QuantitativeValue",
                            "value": 9906,
                            "unitText": "byte"
                        },
                        "encodingFormat": "text/csv",
                        "relatedLink": [
                            {
                                "@type": "LinkRole",
                                "linkrelationship": "metthodDescription",
